import random
kelimeler = ["gözəl ","məlumat ","sual","sağlam ","buraxmaq","yaraşıqlı","su","etmək","işlədmək","deyil","görmək",
             "yenidən", "həssas", "sanki", "manat", "oynamaq", "çiçək", "şəhər", "yüksəlmək", "çabalamaq", "varlıq", "diyar",
             "güvən", "gərək", "müalicə", "bir", "rahat", "soyuq", "hava", "kitab", "paylaşmaq", "hesap", "vücud",
             "torpaq", "kitab", "sistem", "xoşallanmaq", "çəkilmək", "texnik", "yaxınlaşmaq", "il", "tarix", "dəqiq", "qaqaş",
             "nazik", "dəyər", "orda", "qarşılıq","vermək", "sahib", "artıq", "kişi", "digər", "dönmək", "yenə", "enlikürək",
             "dəftər", "hadisə", "tapmaq", "göz", "dövlət", "qabağ", "tələb", "baxmaq", "üstündə", "belə", "bəzi", "başlamaq",
             "tutmaq", "birə", "heç", "göstərmək", "hovuz", "kimi", "hal", "doğru", "orta", "başqa", "böyük", "getmək",
             "yeni", "çox", "soruşmaq", "onlar", "açmaq", "dəniz", "həmişə", "səs", "anlamaq", "dəli", "saat", "neçə",
             'aydın', 'və', 'aparmaq', 'bu', 'üçün', 'sevgi', 'qığılcım', 'demək', 'delfin', 'maral', 'nə', 'balıq', 'daha', 'almaq',
             'var', 'kənd', 'qonaq', 'ildə', 'mənim', 'ancaq', 'sonra', 'qismət', 'yer', 'məhəbbət', 'insan', 'sənsiz', 'dalğalı',
             'istəmək', 'yubley', 'çıxmaq', 'görmək', 'gün', 'bizim', 'zalım', 'iş', 'ara', 'məsafə', 'lakin', 'bilmək', 'elçi', 'həyat',
             'yazmaq', 'uşaq', 'iki', 'baxmaq', 'çalışmaq', 'sevda', 'böyük', 'yox', 'bitirmək', 'yol', 'qalmaq', 'nədən', 'yolçu',
             'söhbət', 'dalğalı', 'yaxşı', 'qadın', 'ev', 'ordu', 'axtarmaq', 'susmaq', 'söz', 'önəmli', 'dünya',
             'baş', 'status', 'yan', 'keçmək', 'sən', 'qoyun', 'təzə', 'əvvəlcə', 'başqa', 'telefon', 'məxrəc', 'çay', 'girmək', 'ölkə',
             'yemək', 'qaş', 'oba', 'işıq', 'bütün', 'qarşı', 'tapmaq', 'qələm', 'yaşamaq', 'düşünmək', 'eyni', 'iç', 'dərya',
             'ər', 'qabıq', 'gözləmək', 'ilk', 'burun', 'başlanğıc', 'son', 'çətin', 'şəkil', 'vacib', 'yüz', 'yağış', 'görmək', 'gündüz',
             'alt', 'gətirmək', 'işçi', 'çünki', 'tərəf', 'indi', 'adam', 'onun', 'qar', 'əks', 'qapı', 'səs', 'həmkar',
             'doğru', 'durmaq', 'qız', 'bütün', 'çəkmək', 'danışmaq', 'pul', 'düşmək', 'ata', 'az', 'bəzi', 'baba', 'hayat',
             'sadece', 'küçük', 'fazla', 'bilgi', 'ay', 'akvarium', 'açar', 'sevmək', 'yenə', 'sağlamaq', 'nəticə', 'istifadəçi', 'çöl',
             'ad', 'məsələ', 'saniyə', 'döndərmək', 'açmaq', 'oturmaq', 'gül', 'qol', 'dəqiqə', 'saat', 'yaş', 'problem', 'ağac',
             'sahil', 'sıra', 'cərgə', 'hasar', 'gündəlik', 'atmaq', 'tutmaq', 'diş', 'tərcümə', 'qaçmaq', 'yorğun', 'reklam', 'misal',
             'qum', 'biraz', 'zor', 'biləsuvar', 'bu', 'tənha', 'tək', 'sistem', 'birlikdə', 'dul', 'nömrə', 'aldanmaq', 'gənc',
             'qan', 'darağ', 'maşın', 'tıncıxmaq', 'gecə', 'xəritə', 'bizon', 'şifrə', 'donmaq', 'uzun', 'maska', 'saç', 'yas',
             'dost', 'çeşid', 'ailə', 'şar', 'oxumaq', 'balon', 'əqrəb', 'güc', 'balina', 'dürüst', 'kalonka', 'əlaqə', 'münasibət',
             'ətraf', 'köhnə', 'kifayət', 'müsəlman', 'cümlə', 'kənar', 'küçə', 'bəy', 'sarı', 'kəsmək', 'seriya', 'şəxsi', 'ağıl',
             'səssiz', 'pak', 'əymək', 'gərək', 'ayrılıq', 'məna', 'yüksək', 'bank', 'gəlin', 'sıra', 'daşımaq', 'geri', 'toplanmaq',
             'nardaran', 'maddə', 'məhsul', 'qərar', 'kor', 'yağlamaq', 'saymaq', 'fərqli', 'qrup', 'otağ', 'bildirçin', 'kanal', 'xəbər',
             'sürmək', 'xına', 'gələcək', 'millət', 'soğan', 'arxa', 'qazanmaq', 'yazı', 'dərs', 'açıq', 'öyrənmək', 'qəza',
             'dil', 'şirkət', 'qaynaq', 'bitki', 'program', 'davam', 'sürüşmək', 'reng', 'müəllim', 'haqq', 'inanmaq',
             'dərslik', 'acı', 'parça', 'qəzet', 'bərbər', 'təbib', 'toxunmaq', 'tanımaq', 'kredit', 'həkim', 'maaş',
             'vəzifə', 'məqsəd', 'bölgə', 'film', 'dayı', 'köçmək', 'haqqında', 'qayıtmaq', 'lezva', 'kür', 'ikinci',
             'təyyarə', 'bərbər', 'elektrik', 'nəsil', 'qara', 'fəsil', 'fikirləşmək', 'milyon', 'oyuncaq', 'süpürgə', 'təməl',
             'yaratmaq', 'çatmaq', 'sınamaq', 'keçirmək', 'kal', 'meyvə', 'fəqət', 'eşq', 'rəsim', 'işıq', 'içmək',
             'xanım', 'xidmət', 'ehtiyac', 'nöqtə', 'qayda', 'cansız', 'oyun', 'artırmaq', 'təkrar', 'tənbəl', 'qısa', 'asan',
             'dəsmal', 'oraq', 'səcdə', 'razılaşmaq', 'rəssam', 'diqqət', 'kompyuter', 'printer', 'gələcək', 'üzüm',
             'isti', 'oğlaq', 'dinləmək', 'uyğun', 'şirvan', 'yeniyetmə', 'metr', 'unutmaq', 'yerimək', 'stol', 'mürgüləmək',
             'çətir', 'ağız', 'duyğu', 'quraşdırmaq', 'hələ', 'şagird', 'birçox', 'izləmək', 'dərəcə', 'mümkün', 'karandaş',
             'divar', 'şəkil', 'sənət', 'menyu', 'xəstəlik', 'qürur', 'televizor', 'bulud', 'masa', 'ölmək', 'komanda', 'üst',
             'kafe', 'musiqi', 'ayılmaq', 'enerji', 'universitet', 'idman', 'güzgü', 'can', 'kilid', 'sayğac', 'ölüm',
             'kofe', 'qaranquş', 'cənnət', 'baha', 'ucuz', 'onlar', 'sabah', 'internet', 'mühəndis', 'mənzərə',
             'mərkəz', 'məchul', 'yerində', 'düzənlik', 'qəsəbə', 'tox', 'aşağı', 'cavab', 'yatmaq', 'səhər', '', 'axşam',
             'sübut', 'götürmək', 'qatılmaq', 'yoxsa', 'paltar', 'ödəmək', 'milliön', 'mesaj', 'xəstə', 'şəhər', 'enmek',
             'cücə', 'stul', 'həftə', 'tıxac', 'hesap', 'avtomobil', 'yad', 'yer', 'mətbəx', 'vərəq', 'lakin',
             'kölgə', 'ayrı', 'qiymət', 'haqqında', 'ağırlıq', 'kassa', 'yalnız', 'hazırlamaq', 'pəncərə', 'sonunda', 'yavaş',
             'lazım', 'dəyər', 'qoca', 'yanlış', 'varlıq', 'artım', 'beton', 'quyu', 'satış', 'içəridə', 'lüks', 'məhtəl',
             'qaya', 'dağ', 'xeyir', 'qorumaq', 'qatil', 'qandal', 'məhkum', 'əl', 'zebra', 'heyvan', 'savaş',
             'mal', 'sac', 'bankrot', 'mala', 'dəyiştirmək', 'dörd', 'düzəltmək', 'səhifə', 'tələbə', 'qurmaq', 'beş',
             'iqtisadiyyat', 'geniş', 'yandırmaq', 'qoxu', 'sağ', 'çimərlik', 'əsr', 'caddə', 'bazar', 'rüzgar', 'quldur', 'sinif',
             'şükür', 'çıxmaq', 'ağır', 'bayraq', 'guşə', 'siqaret', 'daş', 'kəlimə', 'bina', 'eşmək', 'üzmək', 'parti', 'yataq',
             'çəkilmək', 'qorxmaq', 'fəth', 'səbəbkar','sol', 'külək', 'yağ', 'anmaq', 'alışqan', 'vurmaq', 'gülmək', 'darıxmaq',
             'satmaq', 'şir', 'göndermək', 'bacarıq', 'firma', 'hürkütmək', 'ürək', 'hərarət', 'puş', 'şərt', 'surət', 'künc',
             'yaralı', 'model', 'balık', 'məhəllə', 'görüş', 'vətən', 'qonağlıq', 'miqdar', 'birinci', 'meydan', 'ölçü',
             'seçmek', 'zərgər', 'məktəb', 'baxça', 'çörək', 'boy', 'qızdırmaq', 'dolu', 'qurutmaq', 'sənaye', 'uçmaq',
             'yardım', 'qarşılaşmaq', 'market', 'xumarlanmaq', 'yoxlama', 'məşhur', 'balaca', 'gəzmək', 'çiçək', 'işarə',
             'kömək', 'ağcaqanad', 'istək', 'ötən', 'yoxlamaq', 'yoluxmaq', 'addım', 'nərd', 'oğru', 'icazə', 'korku',
             'təhsil', 'polis', 'şər', 'acılamaq', 'fikir', 'tez', 'sap', 'məşğul', 'yosun', 'atəş', 'fərq',
             'yaşma', 'yaşlı', 'sızıldamaq', 'qoşulmaq', 'məhlə', 'mütləq', 'yemək', 'federasiya', 'ləngitmək', 'dayanmaq', 'dar',
             'qaç', 'yaşıllaşdırılma', 'zövq', 'görüntü', 'pəri', 'ders', 'deputat', 'alov', 'canlı', 'silah', 'aso',
             'mükafat', 'xlor', 'fərqləndirmək', 'müzakirə', 'sinema', 'dəyişkən', 'hedef', 'yuxulamaq', 'dostluq', 'yanmaq',
             'mükafatlandırmaq', 'nanə', 'basmaq', 'kenar', 'kontrol', 'çevirmek', 'din', 'güçlü', 'henüz', 'plan', 'beyin',
             'elektrik', 'karı', 'üstünde', 'et', 'sağlanmak', 'söylenmek', 'çizgi', 'uç', 'üye', 'cilt', 'ruh',
             'sevgili', 'yaklaşmak', 'süreç', 'bakış', 'bilim', 'ileri', 'ifade', 'beden', 'hatırlamak', 'kaza',
             'iyice', 'dağ', 'kapatmak', 'adım', 'ciddi', 'çözüm', 'etkilemek', 'belediye', 'gelişme', 'seçim',
             'ağlamak', 'bağlı', 'kavram', 'artırmak', 'faaliyet', 'zarar', 'derin', 'salon', 'çeşit', 'kesilmek',
             'seyretmek', 'birden', 'içermek', 'sayılmak', 'toplamak', 'aşmak', 'bağırmak', 'sorumluluk', 'davranmak',
             'mektup', 'soğuk', 'canlı', 'idiekeylem', 'makine', 'yararlanmak', 'yaşlı', 'boş', 'acaba', 'maç', 'yönetici',
             'getirilmek', 'metre', 'tutulmak', 'kalite', 'bitki', 'değişiklik', 'ilaç', 'kredi', 'yasa', 'başarılı',
             'birer', 'imkan', 'ceza', 'herşey', 'incelemek', 'top', 'uzman', 'doldurmak', 'kanal', 'mekân', 'uymak',
             'yıllık', 'dolayısıyla', 'yazılmak', 'ait', 'parmak', 'saymak', 'atılmak', 'belirlemek', 'normal', 'hele',
             'ilke', 'kırmızı', 'rol', 'şarkı', 'eleman', 'hazır', 'benzemek', 'birşey', 'hoca', 'boy', 'günlük', 'politika',
             'suç', 'niye', 'sahne', 'sokmak', 'adet', 'koltuk', 'kurtarmak', 'sanatçı', 'tercihetmek', 'uzanmak', 'aşama',
             'eklemek', 'orman', 'ayırmak', 'düzen', 'faiz', 'genellikle', 'herzaman', 'hikaye', 'hücre', 'ora', 'roman',
             'vergi', 'yakmak', 'ağabey', 'basın', 'destek', 'giymek', 'hata', 'sınır', 'birlik', 'eser', 'karşılamak',
             'yarı', 'yeterli', 'birey', 'karanlık', 'otobüs', 'sanayi', 'bebek', 'vatandaş', 'bakan', 'kere', 'millet',
             'reklam', 'yükselmek', 'boyut', 'dergi', 'enflasyon', 'sosyal', 'birisi', 'geçmiş', 'hastahane', 'olma',
             'toplantı', 'gazeteci', 'içerisi', 'inanç', 'nitelik', 'üzeri', 'bitirmek', 'gerçekleşmek', 'giriş', 'rahat',
             'toplam', 'beraber', 'dükkan', 'gizli', 'benzer', 'deri', 'dönüşmek', 'mücadele', 'problem', 'servis', 'tedavi',
             'yeşil', 'bakanlık', 'baskı', 'tepki', 'cümle', 'dilemek', 'özgürlük', 'gene', 'kimlik', 'mesele', 'üçüncü',
             'belirlenmek', 'değerlendirmek', 'ilginç', 'sürücü', 'süt', 'yakalamak', 'eşya', 'uluslararası', 'aday',
             'ağırlık', 'milyar', 'sağlılklı', 'sıkıntı', 'tanrı', 'tavır', 'toplumsal', 'yayın', 'dikkatetmek', 'sonderece',
             'toplanmak', 'yatırım', 'hafif', 'karışmak', 'tehlike', 'vakit', 'daire', 'fırsat', 'işlemek', 'karıştırmak',
             'katkı', 'öykü', 'tamamen', 'uçak', 'yanıt', 'doğa', 'evlenmek', 'burun', 'çıkar', 'elbette', 'işçi', 'işletme',
             'kısaca', 'mağaza', 'medya', 'yüzünden', 'artış', 'çıkarılmak', 'kamu', 'sigorta', 'yaz', 'yürek', 'belge',
             'çaba', 'hergün', 'ifadeetmek', 'risk', 'sözetmek', 'sözcük', 'demokrasi', 'tuz', 'cami', 'çağ', 'düşük',
             'etraf', 'hızla', 'olanak', 'organ', 'öldürmek', 'öteki', 'sene', 'bozulmak', 'ilgilenmek', 'meyve', 'takılmak',
             'tatlı', 'bacak', 'değişim', 'kanun', 'rüzgar', 'cumhuriyet', 'geliştirmek', 'tarz', 'yedi', 'azalmak',
             'bağlamak', 'ceptelefonu', 'iletişim', 'müdür', 'otel', 'yayımlanmak', 'zevk', 'binmek', 'güvenlik', 'hukuk',
             'kılmak', 'modern', 'okur', 'silah', 'talep', 'yıldız', 'yoğun', 'asker', 'basit', 'denilmek', 'gaz',
             'uygulama', 'üretilmek', 'beyan', 'besin', 'dün', 'görüşmek', 'yaklaşık', 'alışveriş', 'bilinç', 'çerçeve',
             'lazım', 'mevcut', 'tüketici', 'uzatmak', 'yönelik', 'at', 'bağlanmak', 'mesela', 'neredeyse', 'site',
             'yardımcıolmak', 'abla', 'çiçek', 'hepsi', 'saygı', 'ücret', 'yetenek', 'kilo', 'paylaşmak', 'sert', 'yanısıra',
             'çay', 'gider', 'kesin', 'zengin', 'asla', 'laf', 'örgüt', 'ticaret', 'yaptırmak', 'boyun', 'cihaz',
             'denge', 'giderek', 'sırt', 'dolayı', 'kahve', 'kas', 'meclis', 'öteki', 'uğraşmak', 'adres', 'belirtilmek',
             'paşa', 'sıcaklık', 'tamam', 'güven', 'marka', 'yaprak', 'yarar', 'yayılmak', 'akmak', 'çizmek', 'düşünülmek',
             'gönül', 'hayal', 'ilerlemek', 'şarap', 'yukarıda', 'altın', 'düzenlemek', 'satınalmak', 'sunulmak', 'temiz',
             'vitamin', 'ek', 'geç', 'hareketetmek', 'yumurta', 'aşırı', 'eylem', 'istenmek', 'kesim', 'kriz', 'birim',
             'kapanmak'
             ]


def kelime_sec():
    return random.choice(kelimeler)
